Repository DeveloperAcademy-POSTECH/2024-MC2-M09-PoHyoja, pull requests merged in 2025-02, with the labels that each got.

#187 Refactor: #185 foldering
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Data/Local/DataSource/EntityDataSource.swift
  PicCharge/PicCharge/Data/Local/DataSource/PersistenceStack.swift
  PicCharge/PicCharge/Data/Local/Interface/LocalRepository.swift
  PicCharge/PicCharge/Data/Local/Model/PhotoEntity.swift
  PicCharge/PicCharge/Data/Local/Model/UserEntity.swift
  PicCharge/PicCharge/Data/Local/Repository/DefaultLocalRepository.swift
  PicCharge/PicCharge/Data/Remote/Interface/RemoteRepository.swift
  PicCharge/PicCharge/Data/Remote/Model/ConnectionRequestsDTO.swift
  PicCharge/PicCharge/Data/Remote/Model/PhotoDTO_V0.swift
  PicCharge/PicCharge/Data/Remote/Model/PhotoDTO_V1.swift
  PicCharge/PicCharge/Data/Remote/Model/PhotoShareDTO.swift
  PicCharge/PicCharge/Data/Remote/Model/UserDTO.swift
  PicCharge/PicCharge/Data/Remote/Repository/DefaultRemoteRepository.swift
  PicCharge/PicCharge/Data/Remote/Repository/Deprecated/FirestoreService.swift
  PicCharge/PicCharge/Data/Remote/Repository/Deprecated/FirestoreServiceError.swift
  PicCharge/PicCharge/Data/Remote/Repository/FireStoreError.swift
  PicCharge/PicCharge/Global/CommonModifiers/DIContainerModifier.swift
  PicCharge/PicCharge/Global/Helper/GlobalAlert.swift
  PicCharge/PicCharge/Global/Helper/HapticManager.swift
  PicCharge/PicCharge/Global/Helper/NavigationManager.swift
  PicCharge/PicCharge/Global/Utils/BatteryCalculator.swift
  PicCharge/PicCharge/Global/Utils/Utils.swift
  PicCharge/PicCharge/Helper/GlobalAlert.swift
  PicCharge/PicCharge/Model/Photo.swift
  PicCharge/PicCharge/Model/User.swift
  PicCharge/PicCharge/View/Scene/Auth/ConnectUserView.swift
  PicCharge/PicCharge/View/Scene/Auth/EmailLoginView.swift
  PicCharge/PicCharge/View/Scene/Auth/MainLoginView.swift
  PicCharge/PicCharge/View/Scene/Auth/SignUpEmailPasswordView.swift
  PicCharge/PicCharge/View/Scene/Auth/SignUpNameView.swift
  PicCharge/PicCharge/View/Scene/Auth/SignUpRoleView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildAlbumDetailView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildAlbumView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildCameraView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildMainView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildSelectGalleryView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildSendCameraView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildSendGalleryView.swift
  PicCharge/PicCharge/View/Scene/Child/ChildTabView.swift
  PicCharge/PicCharge/View/Scene/Parent/ParentAlbumDetailView.swift
  PicCharge/PicCharge/View/Scene/Parent/ParentAlbumView.swift
  PicCharge/PicCharge/View/Scene/Setting/SettingView.swift
  PicCharge/PicCharge/View/Scene/Shared/AppNavigationView.swift
  PicCharge/PicCharge/View/Scene/Shared/ContentView.swift
  PicCharge/PicCharge/View/SignUpView.swift
  PicCharge/PicCharge/ViewModel/PhotoViewModel.swift
  PicCharge/PicCharge/ViewModel/UserViewModel.swift
  PicCharge/UserConnectingService.swift
Labels: Ready to Review, Refactor

#189 Feat: #188 (ReleaseBranch) 사용자 이름 선반영
  PicCharge/PicCharge/Helper/NavigationManager.swift
  PicCharge/PicCharge/View/Auth/SignUpEmailPasswordView.swift
  PicCharge/PicCharge/View/Auth/SignUpNameView.swift
  PicCharge/PicCharge/View/Components/AppleLoginBtn.swift
  PicCharge/UserViewModel.swift
Labels: Feat, Ready to Review

#184 Release/v1.0.0
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Global/Helper/NavigationManager.swift
  PicCharge/PicCharge/View/Components/AppleLoginBtn.swift
  PicCharge/PicCharge/View/Scene/Auth/SignUpEmailPasswordView.swift
  PicCharge/PicCharge/View/Scene/Auth/SignUpNameView.swift
  PicCharge/PicCharge/ViewModel/UserViewModel.swift
Labels: In Progress, Release

#196 Fix/photo memory
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Data/Local/Model/PhotoEntity.swift
  PicCharge/PicCharge/ImageProcessing/CGSize+.swift
  PicCharge/PicCharge/ImageProcessing/Data+Downsampling.swift
  PicCharge/PicCharge/ImageProcessing/ImageCache.swift
  PicCharge/PicCharge/View/Components/AsyncSquareImage.swift
  PicCharge/PicCharge/View/Scene/Child/ChildAlbumView.swift
  PicCharge/PicCharge/View/Scene/Parent/ParentAlbumView.swift
Labels: Bug, Ready to Review

#197 Fix: #192 버튼 아이콘 수정
  PicCharge/PicCharge/View/Scene/Child/ChildMainView.swift
Labels: Feat, Ready to Review

#198 Fix: #190 자식 배터리 0 일때 UI 수정
  PicCharge/ParentWidget/ChildWidget.swift
  PicCharge/PicCharge/View/Scene/Child/ChildCameraView.swift
Labels: Feat, Ready to Review

#200 Fix: widget low quality
  PicCharge/ParentWidget/ParentWidget.swift
  PicCharge/ParentWidget/ParentWidgetBundle.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Global/Extensions/UIImage+.swift
  PicCharge/PicCharge/ImageProcessing/CGSize+.swift
Labels: Bug, Ready to Review

#199 Feat: app store 별점 및 문의기능 추가
  PicCharge/PicCharge/Global/Helper/GlobalAlert.swift
  PicCharge/PicCharge/Global/Literals/Icon.swift
  PicCharge/PicCharge/Global/Literals/URL.swift
  PicCharge/PicCharge/View/Scene/Setting/SettingView.swift
Labels: Feat, Ready to Review

#202 Release: v1.1.0
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Mock/MockLocalRepository.swift
  PicCharge/PicCharge/Mock/MockRemoteRepository.swift
  PicCharge/PicCharge/Mock/Photo+Mock.swift
  PicCharge/PicCharge/Mock/PreviewDIContainerModifier.swift
  PicCharge/PicCharge/Mock/User+Mock.swift
  PicCharge/PicCharge/Resources/GoogleService-Info.plist
Labels: Release

#206 [Release] v1.1.1
  PicCharge/PicCharge.xcodeproj/project.pbxproj
Labels: Bug, Release
