Repository DeveloperAcademy-POSTECH/2024-MC2-M09-PoHyoja, pull requests merged in 2025-01, with the labels that each got.

#151 Refactor/dependency
  PicCharge/DIContainerModifier.swift
  PicCharge/LocalStorageService.swift
  PicCharge/MockLocalStorageService.swift
  PicCharge/MockRemoteStorageServiceImpl.swift
  PicCharge/ParentWidget/ChildWidget.swift
  PicCharge/ParentWidget/ParentWidget.swift
  PicCharge/PhotoViewModel.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/App/AppNavigationView.swift
  PicCharge/PicCharge/App/PicChargeApp.swift
  PicCharge/PicCharge/Helper/NavigationManager.swift
  PicCharge/PicCharge/Model/ConnectionRequestsDTO.swift
  PicCharge/PicCharge/Model/DomainConvertible.swift
  PicCharge/PicCharge/Model/Photo/Photo.swift
  PicCharge/PicCharge/Model/Photo/PhotoDTO.swift
  PicCharge/PicCharge/Model/Photo/PhotoEntity.swift
  PicCharge/PicCharge/Model/Photo/PhotoShareDTO.swift
  PicCharge/PicCharge/Model/User/User.swift
  PicCharge/PicCharge/Model/User/UserDTO.swift
  PicCharge/PicCharge/Model/User/UserEntity.swift
  PicCharge/PicCharge/Service/FirestoreService.swift
  PicCharge/PicCharge/View/Auth/ConnectUserView.swift
  PicCharge/PicCharge/View/Auth/LoginView.swift
  PicCharge/PicCharge/View/Auth/SelectRoleForSignUpView.swift
  PicCharge/PicCharge/View/Child/ChildAlbumDetailView.swift
  PicCharge/PicCharge/View/Child/ChildAlbumView.swift
  PicCharge/PicCharge/View/Child/ChildMainView.swift
  PicCharge/PicCharge/View/Child/ChildSendCameraView.swift
  PicCharge/PicCharge/View/Child/ChildSendGalleryView.swift
  PicCharge/PicCharge/View/Child/ChildTabView.swift
  PicCharge/PicCharge/View/ContentView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumDetailView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumView.swift
  PicCharge/PicCharge/View/Setting/SettingView.swift
  PicCharge/RemoteStorageService.swift
  PicCharge/UserConnectingService.swift
  PicCharge/UserViewModel.swift
Labels: Feat, In Progress, Refactor

#153 Feat: #152 SwiftDataRepository 구현
  PicCharge/LocalStorageService.swift
  PicCharge/MockLocalStorageService.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Model/Photo/Photo.swift
  PicCharge/PicCharge/Model/Photo/PhotoEntity.swift
  PicCharge/PicCharge/Model/User/UserEntity.swift
  PicCharge/PicCharge/Service/PersistenceStack.swift
  PicCharge/PicCharge/Service/SwiftDataRepository.swift
  PicCharge/PicCharge/Service/SwiftDataService.swift
  PicCharge/PicChargeTests/LocalStorageServiceTests.swift
Labels: Feat, Ready to Review

#157 Feat: #154 FireStoreRepository 구현
  PicCharge/MockRemoteStorageServiceImpl.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Model/Photo/PhotoDTO.swift
  PicCharge/PicCharge/Model/User/UserDTO.swift
  PicCharge/PicCharge/Service/FireStoreError.swift
  PicCharge/PicCharge/Service/FireStoreRepository.swift
  PicCharge/RemoteStorageService.swift
Labels: Ready to Review, Refactor

#160 Feat: #158 PhotoViewModel 적용
  PicCharge/DIContainerModifier.swift
  PicCharge/GlobalAlertModifier.swift
  PicCharge/LocalStorageService.swift
  PicCharge/MockLocalStorageService.swift
  PicCharge/MockRemoteStorageServiceImpl.swift
  PicCharge/PhotoViewModel.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/App/PicChargeApp.swift
  PicCharge/PicCharge/Helper/GlobalAlert.swift
  PicCharge/PicCharge/Helper/NavigationManager.swift
  PicCharge/PicCharge/Model/Photo/Photo.swift
  PicCharge/PicCharge/Model/User/User.swift
  PicCharge/PicCharge/Resources/PicCharge.entitlements
  PicCharge/PicCharge/Service/FireStoreError.swift
  PicCharge/PicCharge/Service/FireStoreRepository.swift
  PicCharge/PicCharge/Service/PersistenceStack.swift
  PicCharge/PicCharge/Service/SwiftDataRepository.swift
  PicCharge/PicCharge/Service/SwiftDataService.swift
  PicCharge/PicCharge/View/Child/ChildAlbumDetailView.swift
  PicCharge/PicCharge/View/Child/ChildAlbumView.swift
  PicCharge/PicCharge/View/Child/ChildCameraView.swift
  PicCharge/PicCharge/View/Child/ChildMainView.swift
  PicCharge/PicCharge/View/Child/ChildSelectGalleryView.swift
  PicCharge/PicCharge/View/Child/ChildSendCameraView.swift
  PicCharge/PicCharge/View/Child/ChildSendGalleryView.swift
  PicCharge/PicCharge/View/Child/ChildTabView.swift
  PicCharge/PicCharge/View/Components/ChildLoadingView.swift
  PicCharge/PicCharge/View/Components/SquareImage.swift
  PicCharge/PicCharge/View/ContentView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumDetailView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumView.swift
  PicCharge/PicCharge/View/Setting/SettingView.swift
  PicCharge/PicChargeTests/LocalStorageServiceTests.swift
  PicCharge/RemoteStorageService.swift
  PicCharge/UserViewModel.swift
Labels: Feat, In Progress

#159 Refactor: #149 앱과 위젯 시간 감소 로직 통합
  PicCharge/ParentWidget/ChildWidget.swift
  PicCharge/ParentWidget/ParentWidget.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Global/BatteryCalculator.swift
  PicCharge/PicCharge/View/Child/ChildMainView.swift
Labels: Ready to Review, Refactor

#174 Feat: #173 위젯 딥링크 구현
  PicCharge/ParentWidget/AppIntent.swift
  PicCharge/ParentWidget/ChildWidget.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Global/Extensions/URL+.swift
  PicCharge/PicCharge/View/ContentView.swift
Labels: Feat, Ready to Review

#176 Refactor: #162 사진 Sync 로직 변경
  PicCharge/LocalStorageService.swift
  PicCharge/PhotoViewModel.swift
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/Model/Photo/Photo.swift
  PicCharge/PicCharge/Model/Photo/PhotoEntity.swift
  PicCharge/PicCharge/Model/Photo/PhotoShareDTO.swift
  PicCharge/PicCharge/Service/SwiftDataRepository.swift
  PicCharge/PicCharge/View/Child/ChildAlbumDetailView.swift
  PicCharge/PicCharge/View/Child/ChildAlbumView.swift
  PicCharge/PicCharge/View/Components/AsyncSquareImage.swift
  PicCharge/PicCharge/View/Components/SquareImage.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumDetailView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumView.swift
Labels: Feat, Ready to Review, Refactor

#180 Feat: #179 Reaction 업데이트 기능 추가
  PicCharge/PhotoViewModel.swift
  PicCharge/PicCharge/Model/Photo/Photo.swift
  PicCharge/PicCharge/Service/FireStoreRepository.swift
  PicCharge/PicCharge/View/Child/ChildAlbumDetailView.swift
  PicCharge/PicCharge/View/Child/ChildMainView.swift
  PicCharge/PicCharge/View/Parent/ParentAlbumDetailView.swift
Labels: Feat, Ready to Review

#182 Feat: #175 애플 로그인 구현
  PicCharge/PicCharge.xcodeproj/project.pbxproj
  PicCharge/PicCharge/View/Auth/ConnectUserView.swift
  PicCharge/PicCharge/View/Auth/MainLoginView.swift
  PicCharge/PicCharge/View/Auth/SignUpNameView.swift
  PicCharge/PicCharge/View/Auth/SignUpRoleView.swift
  PicCharge/PicCharge/View/Components/AppleLoginBtn.swift
  PicCharge/PicCharge/View/Setting/SettingView.swift
  PicCharge/UserViewModel.swift
Labels: Feat, Ready to Review
